
services:
  typedb:
    image: public.ecr.aws/r5d0x2q7/typedb:arm
    container_name: typedb
    volumes:
      - geminos:/data/typedb:rw
      - ~/Desktop/causeway-docker/volumes/typedb:/typedb:rw
    networks:
      causewaynet:
        ipv4_address: 172.24.2.1
    ports:
      - "1729:1729"
    restart: always
  gui:
    image: public.ecr.aws/r5d0x2q7/causewaygui:dscpro-1.3.1.2
    container_name: "causewaygui"
    volumes:
      - geminos:/root:rw
      - geminos:/data:rw
      - ~/Desktop/causeway-docker/volumes/frontend:/frontend:rw
    networks:
      causewaynet:
        ipv4_address: 172.24.2.2
    ports:
      - "1880:1880"
    depends_on:
      - "typedb"
    restart: always
  api:
    image: public.ecr.aws/r5d0x2q7/causewayapi:latest
    container_name: "causewayapi"
    volumes:
      - geminos:/data:rw
      - geminos:/root:rw
      - ~/Desktop/causeway-docker/volumes/backend:/backend:rw
    restart: always
    networks:
      causewaynet:
        ipv4_address: 172.24.2.3
    ports:
      - "5001:5001"
    depends_on:
      - gui
      - typedb
networks:
  causewaynet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.24.2.0/16"
volumes:
  geminos:
    driver: local