version: "3"
services:
  typedb:
    image: public.ecr.aws/r5d0x2q7/typedb:arm
    container_name: typedb
    volumes:
      - geminos:/data/typedb:rw
      - ~/Desktop/causeway/volumes/typedb:/typedb:rw
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "1729:1729"
    restart: always
  gui:
    image: public.ecr.aws/r5d0x2q7/causewaygui:dscpro-flowise
    container_name: "causewaygui"
    volumes:
      - geminos:/root:rw
      - geminos:/data:rw
      - ~/Desktop/causeway/volumes/frontend:/frontend:rw
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "1880:1880"
    depends_on:
      - "typedb"
    restart: always
  api:
    image: public.ecr.aws/r5d0x2q7/causewayapi:flowise
    container_name: "causewayapi"
    volumes:
      - geminos:/data:rw
      - geminos:/root:rw
      - ~/Desktop/causeway/volumes/backend:/backend:rw
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "5001:5001"
    depends_on:
      - gui
      - typedb
volumes:
  geminos:
    driver: local